import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import{getFirestore,collection,addDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
const cfg={apiKey:"AIzaSyAF3mfufOYyXktZw56kHmRrw_gdB4Q_1Eg",authDomain:"love-ecom.firebaseapp.com",projectId:"love-ecom",storageBucket:"love-ecom.firebasestorage.app",messagingSenderId:"1010601603461",appId:"1:1010601603461:web:451336359a74215c93d4ec",measurementId:"G-3E6YCK85TE"};
const db=getFirestore(initializeApp(cfg)), $=id=>document.getElementById(id);let visitorName="",noCount=0,finished=false;
const save=(answer)=>{const data={name:visitorName,answer,noPresses:noCount,createdAt:serverTimestamp()};try{const p=addDoc(collection(db,"responses"),data);p.catch(e=>console.error(e));}catch(e){console.error(e)}};
$("go").onclick=()=>{const n=$("n").value.trim();if(!n){$("err").textContent="Please enter your name 💗";return}visitorName=n;$("hello").textContent=`Hey ${n} 💕`;$("name").classList.add("hide");$("q").classList.remove("hide")};$("n").onkeydown=e=>{if(e.key==="Enter")$("go").click()};
$("no").onclick=()=>{if(finished)return;noCount++;const b=$("no"),dx=Math.random()*70-35,dy=Math.random()*42-21,scale=Math.max(.62,1-noCount*.055);b.style.transform=`translate(${dx}px,${dy}px) scale(${scale})`;if(noCount>=6){finished=true;showSad();save("NO")}else $("status").textContent=`Are you sure? 🥺 (${noCount}/6)`};
$("yes").onclick=()=>{if(finished)return;finished=true;showHappy();save("YES")};
function showHappy(){$("q").classList.add("hide");$("result").classList.remove("hide");$("title").textContent="Yayyy! You made Sandip very happy! 💖";$("msg").textContent=`Awww ${visitorName}... 🥰 You just made Sandip's heart very happy! Thank you for choosing Yes! ❤️`;for(let i=0;i<14;i++)setTimeout(spawnHeart,i*80)}
function showSad(){$("q").classList.add("hide");$("result").classList.remove("hide");$("rt").textContent="🧸💔";$("title").textContent="Aww… 🥺💔";$("msg").textContent=`${visitorName}, you pressed No 6 times… Sandip is a little sad now. 💔 But your feelings matter, always. 🥹`}
function spawnHeart(){const h=document.createElement("div");h.className="heart";h.textContent="❤️";h.style.left=20+Math.random()*60+"vw";h.style.top=55+Math.random()*15+"vh";document.body.appendChild(h);setTimeout(()=>h.remove(),1500)}
