import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import{getFirestore,collection,addDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
const cfg={apiKey:"AIzaSyD-autiWDynxIrZKSB53FWaNGSTbxYComU",authDomain:"love-page-d3a05.firebaseapp.com",projectId:"love-page-d3a05",storageBucket:"love-page-d3a05.firebasestorage.app",messagingSenderId:"857612763723",appId:"1:857612763723:web:03cd1b0335015cd05943ce"};
const db=getFirestore(initializeApp(cfg)), $=id=>document.getElementById(id);let visitorName="",noCount=0,finished=false;
const save=async(answer)=>{const data={name:visitorName,answer,noPresses:noCount,createdAt:serverTimestamp()};try{await addDoc(collection(db,"responses"),data);return true}catch(e){console.error("Firestore save error:",e);$("status").textContent="Could not save your response. Please try again.";return false}};
$("go").onclick=()=>{const n=$("n").value.trim();if(!n){$("err").textContent="Please enter your name 💗";return}visitorName=n;$("hello").textContent=`Hey ${n} 💕`;$("name").classList.add("hide");$("q").classList.remove("hide")};$("n").onkeydown=e=>{if(e.key==="Enter")$("go").click()};
$("no").onclick=async()=>{if(finished)return;noCount++;const b=$("no"),dx=Math.random()*70-35,dy=Math.random()*42-21,scale=Math.max(.62,1-noCount*.055);b.style.transform=`translate(${dx}px,${dy}px) scale(${scale})`;if(noCount>=6){finished=true;const ok=await save("NO");if(ok)showSad()}else $("status").textContent=`Are you sure? 🥺 (${noCount}/6)`};
$("yes").onclick=async()=>{if(finished)return;finished=true;const ok=await save("YES");if(ok)showHappy()};
function showHappy(){$("q").classList.add("hide");$("result").classList.remove("hide");$("title").textContent="Yayyy! You made Sandip very happy! 💖";$("msg").textContent=`Awww ${visitorName}... 🥰 You just made Sandip's heart very happy! Thank you for choosing Yes! ❤️`;for(let i=0;i<14;i++)setTimeout(spawnHeart,i*80)}
function showSad(){$("q").classList.add("hide");$("result").classList.remove("hide");$("rt").textContent="🧸💔";$("title").textContent="Aww… 🥺💔";$("msg").textContent=`${visitorName}, you pressed No 6 times… Sandip is a little sad now. 💔 But your feelings matter, always. 🥹`}
function spawnHeart(){const h=document.createElement("div");h.className="heart";h.textContent="❤️";h.style.left=20+Math.random()*60+"vw";h.style.top=55+Math.random()*15+"vh";document.body.appendChild(h);setTimeout(()=>h.remove(),1500)}
